# Generated by Django 6.0 on 2026-01-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0004_alter_userprofile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
