# Generated by Django 6.0 on 2026-01-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
