# Generated by Django 6.0 on 2026-01-08 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0007_passwordresetotp_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='last_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
