# Generated by Django 6.0 on 2026-01-08 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0008_passwordresetotp_last_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('PRODUCT_UPDATED', 'Product Updated'), ('ORDER_COMPLETED', 'Order Completed'), ('CATEGORY_ADDED', 'Category Added')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recent_activity',
                'ordering': ['-created_at'],
            },
        ),
    ]
