# Generated by Django 6.0 on 2026-02-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0009_recentactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
