# Generated by Django 6.0 on 2026-04-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOGIN_SUCCESSFUL', 'Login Successful'), ('REGISTER_SUCCESSFUL', 'Register Successful'), ('USER_BANNED', 'User Banned'), ('USER_UNBANNED', 'User Unbanned'), ('ADMIN_PRIVILEGE_GRANTED', 'Admin Privilege Granted'), ('ADMIN_PRIVILEGE_REVOKED', 'Admin Privilege Revoked'), ('SALE_ADDED', 'Sale Added'), ('SYSTEM', 'System Notification'), ('profile_update', 'Profile Update')], default='SYSTEM', max_length=50),
        ),
    ]
