# Generated by Django 6.0 on 2026-04-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthassessment', '0002_assessmentsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='test_field',
        ),
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='healthassessment.assessmentsession'),
        ),
    ]
