# Generated by Django 6.0 on 2026-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthassessment', '0003_remove_answer_test_field_answer_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
