# Generated by Django 6.0 on 2026-04-14 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthassessment', '0005_assessmenttype_assessmentsession_assessment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='assessment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='healthassessment.assessmenttype'),
        ),
    ]
