# Generated by Django 6.0 on 2026-04-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthassessment', '0006_add_assessment_type_to_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('section', 'question_text')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('assessment_type', 'name')},
        ),
    ]
