# Generated by Django 6.0 on 2026-04-14 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthassessment', '0007_section_question_scoped_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assessment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='healthassessment.assessmenttype'),
        ),
    ]
