# Generated by Django 6.0 on 2026-04-17 14:47

import django.db.models.deletion
import django.utils.timezone
import generic.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthassessment', '0008_add_assessment_type_to_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_id', models.UUIDField(default=generic.models.generate_reference_id, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('risk_level', models.CharField(max_length=50)),
                ('problems', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_report', to='healthassessment.assessmentsession')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'healthassessment_diagnosis_report',
                'managed': True,
            },
        ),
    ]
