# Generated by Django 6.0 on 2026-04-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthassessment', '0009_diagnosisreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisreport',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_reports', to='healthassessment.assessmentsession'),
        ),
    ]
