# Generated by Django 6.0 on 2026-04-18 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthassessment', '0010_alter_diagnosisreport_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreport',
            name='assessment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_reports', to='healthassessment.assessmenttype'),
        ),
    ]
