# Generated by Django 5.2.9 on 2026-04-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthassessment', '0011_diagnosisreport_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
